// WhoIsItFor.js generated by create_surebets_react_vite_project_structure.py
import React from 'react';
import styles from './WhoIsItFor.module.css'; // Assuming CSS Modules

const WhoIsItFor = () => {
  return (
    <div className={styles.whoisitfor}>
      <h2>WhoIsItFor Component</h2>
      {/* Add your component JSX here */}
    </div>
  );
};

export default WhoIsItFor;
