// HowItWorks.js generated by create_surebets_react_vite_project_structure.py
import React from 'react';
import styles from './HowItWorks.module.css'; // Assuming CSS Modules

const HowItWorks = () => {
  return (
    <div className={styles.howitworks}>
      <h2>HowItWorks Component</h2>
      {/* Add your component JSX here */}
    </div>
  );
};

export default HowItWorks;
