// WhyItWorks.js generated by create_surebets_react_vite_project_structure.py
import React from 'react';
import styles from './WhyItWorks.module.css'; // Assuming CSS Modules

const WhyItWorks = () => {
  return (
    <div className={styles.whyitworks}>
      <h2>WhyItWorks Component</h2>
      {/* Add your component JSX here */}
    </div>
  );
};

export default WhyItWorks;
